version: "3"

services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - imersao-12
      
networks:
  imersao-12:
    external: true